# Profile information
name: Pratice
title: Pratice - Tenha uma vida mais saudavel
description: > # this means to ignore newlines until "baseurl:"
  Site construido para a materia de encontrabilidade na Fatec Taquaritinga.
permalink: ':title/'
baseurl: "/fresh" # the subpath of your site, e.g. /blog
url: "artemsheludko.pw" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook: #Add your Facebook
twitter: #Add your Twitter
github: MatheusNobrega

# Contact form
email: matheus.adao.nobrega@gmail.ocm

# Comments
discus-identifier: # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
